import create from "zustand";

const useStore = create((set) => {
  return {
    setPage: (pageName, newState) =>
      set((state) => {
        const pageState = state[pageName];
        return { [pageName]: { ...pageState, ...newState } };
      }),
  };
});

export function updateStoreStateFromController(pageName, newState) {
  useStore.getState().setPage(pageName, newState);
}

const desktopModeProps = {
  ...{
  "Home": {
    "Flex2": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "space-between",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "20px",
        "paddingBottom": "",
        "paddingRight": "40px",
        "paddingLeft": "40px",
        "width": "100%",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "Plus Jakarta Sans",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "absolute",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex3": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "24px",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex4": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "20px",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "TextBox1": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "Plus Jakarta Sans",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Portfolio Creator"
      }
    },
    "TextBox2": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Download CV"
      }
    },
    "Button1": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "8px",
        "paddingBottom": "8px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "16px",
        "textAlign": "center",
        "color": "#fff",
        "opacity": "",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1890ff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": "pointer"
      },
      "custom": {
        "text": "Mail"
      }
    },
    "Menu1": {
      "onClick": false,
      "styles": {
        "display": "none",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "open": false,
        "iconHeight": 24,
        "iconWidth": 24,
        "src": "",
        "strokeColor": "",
        "gap": "",
        "alignRight": true
      }
    },
    "TextBox4": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Mail"
      }
    },
    "TextBox5": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Download CV"
      }
    },
    "Flex5": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex6": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex7": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "60px",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "40px",
        "paddingBottom": "",
        "paddingRight": "40px",
        "paddingLeft": "40px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "Plus Jakarta Sans",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Flex9": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "40px",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": 1,
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Image1": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "256px",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "alt": "profile pic",
        "src": "/app-assets/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg"
      }
    },
    "TextBox6": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "I design products"
      }
    },
    "TextBox7": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "that delight and inspire people"
      }
    },
    "TextBox8": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Hi, I am Shyam!"
      }
    },
    "Flex10": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "row",
        "alignItems": "center",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "",
        "columnGap": "20px",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    },
    "Button2": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "8px",
        "paddingBottom": "8px",
        "paddingRight": "15px",
        "paddingLeft": "15px",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "16px",
        "textAlign": "center",
        "color": "#fff",
        "opacity": "",
        "borderRadius": "2px",
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "#1890ff",
        "backgroundImage": "",
        "backgroundColor": "#1890ff",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": "pointer"
      },
      "custom": {
        "text": "Submit"
      }
    },
    "TextBox9": {
      "onClick": false,
      "styles": {
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "",
        "fontWeight": 400,
        "fontSize": "",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      },
      "custom": {
        "text": "Download CV"
      }
    },
    "Flex11": {
      "onClick": false,
      "styles": {
        "display": "flex",
        "flexDirection": "column",
        "alignItems": "stretch",
        "justifyContent": "flex-start",
        "flexWrap": "nowrap",
        "alignContent": "stretch",
        "rowGap": "10px",
        "columnGap": "",
        "alignSelf": "",
        "flexGrow": "",
        "flexShrink": "",
        "order": "",
        "marginTop": "",
        "marginBottom": "",
        "marginRight": "",
        "marginLeft": "",
        "paddingTop": "",
        "paddingBottom": "",
        "paddingRight": "",
        "paddingLeft": "",
        "width": "",
        "height": "",
        "minWidth": "",
        "minHeight": "",
        "maxWidth": "",
        "maxHeight": "",
        "overflow": "",
        "fontFamily": "Plus Jakarta Sans",
        "fontWeight": 700,
        "fontSize": "32px",
        "textAlign": "left",
        "color": "",
        "opacity": "",
        "borderRadius": "",
        "borderWidth": "",
        "borderStyle": "",
        "borderColor": "",
        "backgroundImage": "",
        "backgroundColor": "",
        "position": "static",
        "float": "none",
        "clear": "none",
        "top": "",
        "left": "",
        "bottom": "",
        "right": "",
        "zIndex": "",
        "outlineStyle": "",
        "outlineColor": "",
        "outlineOffset": "",
        "outlineWidth": "",
        "cursor": ""
      }
    }
  }
}};

const breakpointProps = {
  ...{
  "Home": {
    "991": {
      "Flex4": {
        "styles": {
          "display": "none"
        }
      },
      "Menu1": {
        "styles": {
          "display": "flex"
        }
      },
      "TextBox5": {
        "styles": {
          "width": ""
        }
      },
      "Flex5": {
        "styles": {
          "flexDirection": "column",
          "width": "10rem",
          "alignItems": "flex-end",
          "paddingTop": "10px",
          "rowGap": "4px"
        }
      },
      "Flex6": {
        "styles": {
          "paddingRight": "",
          "alignItems": "center"
        }
      }
    }
  }
}};

function getViewportDimension() {
  const width = Math.max(
    document.documentElement.clientWidth || 0,
    window.innerWidth || 0
  );
  const height = Math.max(
    document.documentElement.clientHeight || 0,
    window.innerHeight || 0
  );
  return { width, height };
}

function getEffectiveBreakpointWidths(pageName, windowWidth) {
  if (breakpointProps[pageName] === undefined) {
    return [];
  }
  const widths = Object.keys(breakpointProps[pageName]);
  return widths
    .filter((curr) => {
      return parseInt(curr) >= windowWidth;
    })
    .sort((a, b) => {
      return parseInt(a) - parseInt(b);
    });
}

/**
 *
 * effective props is combination of
 */
function getEffectivePropsForPage(pageName) {
  const { width } = getViewportDimension();
  // effectiveProps initially has local changes
  let effectiveProps = JSON.parse(
    JSON.stringify(useStore.getState()[pageName])
  );
  const effectiveWidths = getEffectiveBreakpointWidths(pageName, width);
  effectiveWidths.forEach((effectiveWidth) => {
    const compAliases = Object.keys(breakpointProps[pageName][effectiveWidth]);
    compAliases.forEach((compAlias) => {
      const propNames = Object.keys(
        breakpointProps[pageName][effectiveWidth][compAlias]
      );
      propNames.forEach((propName) => {
        effectiveProps[compAlias][propName] = {
          ...useStore.getState()[pageName][compAlias][propName],
          ...breakpointProps[pageName][effectiveWidth][compAlias][propName],
        };
      });
    });
  });
  return effectiveProps;
}

export function setEffectivePropsForPage(pageName) {
  const effectiveProps = getEffectivePropsForPage(pageName);
  useStore.getState().setPage(pageName, effectiveProps);
}

useStore.setState(desktopModeProps);

export default useStore;
